enum ROLES{
  ADMIN = "ADMIN",
  SUPERVISOR = "SUPERVISOR",
  STAFF = "STAFF",
  MEDICAL_STAFF = "MEDICAL_STAFF",
  FEDERATION = "FEDERATION",
  ATHLETE = "ATHLETE",
  GUEST = "GUEST",
}

export default ROLES;
